version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
  - dependency-name: pytz
    versions:
    - "2020.5"
