language: python

# cache pip dependency
cache: pip

sudo: required

python:
  - "2.7"
  - "3.7"

install:
  # - pip install -r requirements.txt --quiet
  - pip install -r requirements.txt

script:
  # - sudo -E env "PATH=$PATH" bash ./script/t -vv mysqlconnpool
  - sudo -E env "PATH=$PATH" bash ./script/t -C -v fsutil
  # - sudo -E env "PATH=$PATH" bash ./script/t -C -v logcollector

# after_success:
#   - pip install python-coveralls && coveralls
